### ISSUE TITLE
Add varnishadm command?

### ISSUE THREAD

**Issue by hkirsman** [wunderio/ddev-drupal#5]
In lando we had this:

```
   varnishadm:
     description: "Runs varnishadm commands"
     service: varnish
     user: root
```
